name: mdBook Journaling
description: A github action that installs mdBook and optional some popular mdbook plugins
author: "Ben Falk"
inputs:
  token:
    description: "Github token"
    required: true
  mdbook-version:
    description: "mdBook version that should be used (e.g. v0.2.2 or 0.2.2)"
    required: false
    default: "latest"
  use-linkcheck:
    description: "Use linkcheck plugin (true / false)"
    required: false
    default: false
  linkcheck-version:
    description: "linkcheck version that should be used (e.g. v0.2.2 or 0.2.2)"
    required: false
    default: "latest"
  use-mermaid:
    description: "Use mermaid plugin (true / false)"
    required: false
    default: false
  mermaid-version:
    description: mermaid version that should be used
    required: false
    default: "latest"
  use-toc:
    description: "Use toc plugin (true / false)"
    required: false
    default: false
  toc-version:
    description: toc version that should be used
    required: false
    default: "latest"
  use-opengh:
    description: "Use open-on-gh plugin (true / false)"
    required: false
    default: false
  opengh-version:
    description: open-on-gh version that should be used
    required: false
    default: "latest"
  use-admonish:
    description: "Use admonish plugin (true / false)"
    required: false
    default: false
  admonish-version:
    description: admonish version that should be used
    required: false
    default: "latest"
  use-katex:
    description: "Use katex plugin (true / false)"
    required: false
    default: false
  katex-version:
    description: katex version that should be used
    required: false
    default: "latest"
  use-journal:
    description: Use journal plugin (true / false)
    required: false
    default: false
  journal-version:
    description: journal version that should be used
    required: false
    default: "latest"
  use-anchors-aweigh:
    description: Use anchors-aweigh plugin (true / false)
    required: false
    default: false
  anchors-aweigh-version:
    description: anchors version that should be used
    required: false
    default: "latest"
runs:
  using: "node20"
  main: "./dist/index.js"
branding:
  icon: "book"
  color: "gray-dark"
